# @host = https://dev.luxdigitalassessoria.com.br
@host = http://localhost:3000


# @name register
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
    "name": "José Augustho",
    "lastName": "Cândido",
    "email": "joseaugustholdddi5760@gmail.com",
    "phone": "3491718593",
    "passwd": "8@Xaracteres",
    "agree": "sim"
}

###

# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "joseaugustholi@gmail.com",
    "passwd": "8*Caracteres"
}

###

@token = {{login.response.body.$.token}}

PUT {{host}}/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{   
    "email": "joseaugusthsfdfolimasil.com"
}

###

//get own user
GET {{host}}/user HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###

#get by id
GET {{host}}/users/
Content-Type: application/json
Authorization: {{token}}