@host = http://localhost:3000


# @name register
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
    "name": "José Augustho",
    "email": "joseaugustholi@gmail.com",
    "phone": "3491718593",
    "passwd": "12345678",
    "confirmPasswd": "12345678"
}

###

# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "joseaugustholi@gmail.com",
    "passwd": "12345678"
}

###

@token = {{login.response.body.$.token}}

PUT {{host}}/user/6761f569c850d470f7d72b12 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{   
    "name": "Paulo Augustho",
    "newPasswd": "123456789",
    "passwd": "1234567890"
}

###

//get own user
GET {{host}}/users HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###

#get by id
DELETE {{host}}/users/
Content-Type: application/json
Authorization: {{token}}