services:
  api:
    build: ./API/
    volumes:
      - /code
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mongodb+srv://jssaugustho:8*Caracteres@users.abex1.mongodb.net/Users?retryWrites=true&w=majority&appName=Users
      - SENHA=12345678901234567890123456789012
      - JWT_SECRET=42455915-2574-4e6e-9a9a-1b026ed24fcc
      - JWT_REFRESH_SECRET=292ab4a3-1344-4fa8-b60e-c625d84003d2
      - EMAIL_USER=joseaugustho@luxdigitalassessoria.com.br
      - EMAIL_PASSWD=8*Caracteres
    develop:
      watch:
        - action: sync+restart
          path: ./API/
          target: /code
  prisma:
    build: ./API/prisma/
    volumes:
      - /code
    ports:
      - 5555:5555
    develop:
      watch:
        - path: ./schema.prisma
          action: sync
          target: /code/prisma/schema.prisma
