@host = http://localhost:3000


# @name register
POST {{host}}/user HTTP/1.1
Content-Type: application/json
Fingerprint: HTTP-VSCODE

{
    "name": "José",
    "lastName": "Augustho",
    "email": "usuariodeteste@gmail.com",
    "phone": "34991718593",
    "passwd": "SenhaDeTeste@123"
}

###

POST {{host}}/email-exists HTTP/1.1
Content-Type: application/json
fingerprint: teste123456789

{
    "email": "joseaugustholi@gmail.com"
}

###

//login
# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json
fingerprint: mozilla0firefox

{
    "email": "usuariodeteste@gmail.com",
    "passwd": "SenhaDeTeste@123"
}

###

@token = {{login.response.body.$.token}}
@refreshToken = {{login.response.body.$.refreshToken}}

###

GET {{host}}/verify-email
Authorization: {{token}}
Content-Type: application/json
fingerprint: mozilla0firefox

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjQxM2Y4NWMzOTdmZTM3NGFhYzIxZiIsInNlc3Npb25JZCI6IjY3ZjQxM2ZlNWMzOTdmZTM3NGFhYzIyMyIsInJhbmQiOiJjYWRjY2IxZS1hM2EzLTQ4ZTgtYjY3Ny02NGE4OTViNTIwZTMiLCJpYXQiOjE3NDQwNTA2MzEsImV4cCI6MTc0NDY1MDYzMX0.s5ZRQvcpA5rVmSIlOcKJHnrZcAhaIqRxqZtby6iOI9M"
}

###

GET {{host}}/email-auth
Authorization: {{token}}
Content-Type: application/json
fingerprint: 9999999999
,
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjEyNmYwMzFlYjU3NjIzYmZkOTZlYiIsInNlc3Npb25JZCI6IjY3ZjQwZjRlNzM1ZWUzYzA1OGRmMTFkNiIsInJhbmQiOiJmNGIwNmFjNS0xYzM5LTQzZTktODE3Yy0yMmE4NmY3MGIzZmEiLCJpYXQiOjE3NDQwNDg5MDEsImV4cCI6MTc0NDY0ODkwMX0.YuiK8tCgrpq2jDYS7AmU0_OIymGwXXnSUretzeqymS4"
}


###


GET {{host}}/resend
Authorization: {{token}}
Content-Type: application/json
fingerprint: mozilla0firefox

###

GET {{host}}/inactivate-session/all HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
fingerprint: 12346579

###

GET {{host}}/inactivate-session HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
fingerprint: 12346579

###

POST {{host}}/send-email-auth HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
fingerprint: 12346579

{
    "email": "joseaugustholi@gmail.com"
}

###

PUT {{host}}/inactivate-session HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
fingerprint: 12346579

{
    "sessionId": "67f29e8f0b3d979a3613314a"
}

###

//refresh token
POST {{host}}/refresh HTTP/1.1
Content-Type: application/json
fingerprint: 9999999999

{
    "refreshToken": "{{refreshToken}}"
}

###

//get logged user
GET {{host}}/user HTTP/1.1
Authorization: {{token}}
fingerprint: mozilla0firefoxs
Content-Type: application/json

###

//get all users
GET {{host}}/users/all HTTP/1.1
Authorization: {{token}}
fingerprint: 123456789
Content-Type: application/json

###

//count all users
GET {{host}}/users/all/count HTTP/1.1
Authorization: {{token}}
fingerprint: 123456789
Content-Type: application/json

###

//update user
PUT {{host}}/user HTTP/1.1
Authorization: {{token}}
fingerprint: 123456789
Content-Type: application/json

{
    "query": {
        "email": "joseaugustholi5@gmail.com"
    },
    "data": {
        "role": "SUPPORT",
        "phone": "34991718593"
    }


